import { StateGraph, type GraphNode, StateSchema,START,END } from "@langchain/langgraph";
import z from "zod";
import { mistralModel, cohereModel, geminiModel } from "../ai/model.ai.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";

const state = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_feedback: z.string().default(""),
    solution_2_feedback: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  const [mistral_response, cohere_response] = await Promise.all([
    mistralModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ]);

  return {
    solution_1: mistral_response.text,
    solution_2: cohere_response.text,
  };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  const judge = createAgent({
    model: geminiModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_feedback: z.string(),
        solution_2_feedback: z.string(),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score between 0 and 10 for each solution, along with feedback explaining the reasoning behind the scores.`,
  });

  const judge_response = await judge.invoke({
    messages: [
      new HumanMessage(`
            Problem: ${problem}
            Solution 1: ${solution_1}
            Solution 2: ${solution_2}
            Please evaluate both solutions and provide scores and feedback.
            `),
    ],
  });

  const { solution_1_score, solution_2_score, solution_1_feedback, solution_2_feedback } = judge_response.structuredResponse;
  return{
    judge:{
        solution_1_score,
        solution_2_score,
        solution_1_feedback,
        solution_2_feedback,
    }
  }
};

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile();

export default async function runGraph(problem: string) {
  const result = await graph.invoke({
    problem: problem,  
  })
  return result;
}

